#include <iostream>
#include <vector>
#include <fstream>
#include <limits>
#include <raylib.h>
#include <cstring>
#include <queue>
#include "graph.h"
#include "DFS.h"
#include "BFS.h"
#include "menu.h"
#include "solver.h"
